services:
  - type: web
    name: yt-downloader
    env: python
    plan: free
    autoDeploy: true

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
